---
fullname: Coq JSON
shortname: coq-json
opam_name: coq-json
organization: liyishuai
action: true
ci_test_dependants: true
synopsis: JSON in Coq
description: From JSON to Coq, and vice versa.
authors:
  - name: Yishuai Li
    email: liyishuai.lys@alibaba-inc.com
license:
  - fullname: BSD 3-Clause "New" or "Revised" License
    identifier: BSD-3-Clause
dependencies:
  - description: '[Parsec](https://github.com/liyishuai/coq-parsec)'
    opam:
      name: coq-parsec
      version: '{ >= "0.2.0" }'
  - description: '[Menhir](http://gallium.inria.fr/~fpottier/menhir/)'
    opam:
      name: menhir
      version: '{ >= "20220210" }'
  - description: "[MenhirLib]\
                  (https://gitlab.inria.fr/fpottier/menhir/-/tree/master/coq-menhirlib/)"
    opam:
      name: coq-menhirlib
      version: '{ >= "20220210" }'
categories:
  - name: Computer Science/Data Types and Data Structures
keywords:
  - name: serialization
  - name: JSON
namespace: JSON
opam-file-maintainer: 'Yishuai Li <liyishuai.lys@alibaba-inc.com>'
supported_coq_versions:
  text: 8.14 or later
  opam: '{ >= "8.14~" }'
tested_coq_opam_versions:
  - version: '8.14'
  - version: '8.15'
  - version: '8.16'
  - version: '8.17'
  - version: '8.18'
  - version: '8.19'
  - version: '8.20'
  - version: 'dev'
dune: true
action_appendix: |2-
            export: 'OPAMWITHTEST'
          env:
            OPAMWITHTEST: true
