---
fullname: Coq JSON
shortname: coq-json
opam_name: coq-json
organization: liyishuai
circleci: true
ci_test_dependants: true
synopsis: JSON in Coq
description: From JSON to Coq, and vice versa.
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
license:
  - fullname: BSD 3-Clause "New" or "Revised" License
    identifier: BSD-3-Clause
dependencies:
  - description: '[Parsec](https://github.com/liyishuai/coq-parsec)'
    opam:
      name: coq-parsec
      version: '{ >= "0.1.0" }'
  - description: '[Menhir](http://gallium.inria.fr/~fpottier/menhir/)'
    opam:
      name: menhir
      version: '{ >= "20210310" }'
  - description: '[MenhirLib](https://gitlab.inria.fr/fpottier/menhir/-/tree/master/coq-menhirlib/)'
    opam:
      name: coq-menhirlib
      version: '{ >= "20210310" }'
categories:
  - name: Computer Science/Data Types and Data Structures
keywords:
  - name: serialization
  - name: JSON
build: |
  ## Building and installation instructions

  The easiest way to install the latest released version of Coq JSON
  is via [OPAM](https://opam.ocaml.org/doc/Install.html):

  ```shell
  opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
  opam install coq-json
  ```

  To instead build and install manually, do:

  ``` shell
  git clone https://github.com/liyishuai/coq-json.git
  cd coq-json
  make   # or make -j <number-of-cores-on-your-machine> 
  make install
  ```
namespace: JSON
opam-file-maintainer: 'Yishuai Li <yishuai@cis.upenn.edu>'
supported_coq_versions:
  text: 8.12 or later
  opam: '{ >= "8.12~" }'
tested_coq_opam_versions:
  - version: '8.12-ocaml-4.11-flambda'
  - version: '8.13-ocaml-4.11-flambda'
  - version: '8.14-ocaml-4.12-flambda'
  - version: '8.15-ocaml-4.12-flambda'
  - version: 'dev-ocaml-4.12-flambda'
test_target: test
